---
- name: Instalar Docker, Kind, kubectl e criar cluster Kubernetes
  hosts: localhost
  connection: local
  become: true

  tasks:
    # ----------------------
    # Instalar dependências
    # ----------------------
    - name: Atualizar o cache do APT
      apt:
        update_cache: true

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    # ----------------------
    # Instalar Docker
    # ----------------------
    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: >
          deb [arch=amd64] https://download.docker.com/linux/debian
          {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Adicionar usuário vagrant ao grupo docker
      user:
        name: vagrant
        groups: docker
        append: true

    # ----------------------
    # Instalar Kind
    # ----------------------
    - name: Baixar o Kind
      get_url:
        url: https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: '0755'

    # ----------------------
    # Instalar kubectl
    # ----------------------
    - name: Baixar o kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.29.3/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    # ----------------------
    # Criar cluster com Kind
    # ----------------------
    - name: Criar diretório de configuração do Kind
      file:
        path: /home/vagrant/kind
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Criar arquivo de configuração do cluster
      copy:
        dest: /home/vagrant/kind/cluster-config.yaml
        content: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
            - role: worker

    - name: Criar o cluster com Kind
      become_user: vagrant
      command: >
        kind create cluster
        --config /home/vagrant/kind/cluster-config.yaml
        --name dev-cluster
